### PR TITLE
two new 'leaking' decals

### PR DESCRIPTION
**Pull request by cloudziq**
usefull decals for variety of maps

### CODE REVIEW

**Review by no-lex — CHANGES_REQUESTED** [review]
Please provide uncompressed (.png) normals as is now expected for all assets: the reason being quality and mod-ability (to prevent lossy modification or remixing later).

**Comment by cloudziq** [comment]
quality is very good as it is now, does there is really a good reason why textures for such SMALL FEATURES need to be ultra HD, and raise game size without any reason?    Does really it hurts so badly about .jpg?    I can delete normals from this entirelly leaving just diffuse, normals are just bonus.

- all my decals source files are anyway in community repo for future use

**Comment by acerspyro** [comment]
Hi @Dziq84,

The reason we ask that everyone contribute their content in the highest quality is to allow other contributors to re-use your work down the line.

JPEG is a lossy format, and as such, we no longer allow them to be submitted as they degrade every time they are modified. We thus require that everyone contribute their images in the lossless .PNG format. Ideally, if available, you should provide the original .PSD or .XCF in the community repository with the layer and filter data.

Cheers,
VLMC

**Comment by cloudziq** [comment]
I understand that reason, that is why I provide source files for all my latest works on /community -  if someone wants to modify,  but in game there is barely a visible difference since I use very low compress on jpg's - all for sake of kepping good quality VS size.  and again - I wouldn't do this decal with normalmap and everything will be right, nobody will even notice... 

OK Misters Devs.. I change this to png later..  or delete normals entirelly, I will see

**Comment by acerspyro** [comment]
If you want to reduce the file size of a PNG file losslessly, I recommend OptiPNG.

http://optipng.sourceforge.net/

Once you have OptiPNG installed, use it as follows in your command line or terminal:
``$ optipng image.png``

**Comment by cloudziq** [comment]
updated, not sure what I should do now.. I made second commit with changes

**Comment by no-lex** [comment]
The specular maps look so dark they're basically pointless. Is there any difference in practice with them enabled? There's no reason to bother enabling the specular/normal channels unless they make a noticeable difference, since it does cost some performance to enable.
Also, they're JPG and not PNG as requested (though my recommendation at first glance is to just remove them unless there's a significant difference)

**Comment by cloudziq** [comment]
You are right, I removed specmaps since these two decals are supposed to not reflect any light.
And still I think that .jpg's is a good choice, since quality is identical, not even mentioning filesize ;p.. If someone want to modify, there are always source files so I don't understand why there is much hate about .jpg among programmers.

**Comment by acerspyro** [comment]
To keep it simple, the JPEG format is meant for photographs, pictures taken with a camera.
JPEG = Joint Photographic Experts Group https://en.wikipedia.org/wiki/JPEG

PNGs, on the other hand, are meant for computer graphics, such as icons and graphics on a website as well as textures.
PNG = Portable Network Graphics https://en.wikipedia.org/wiki/Portable_Network_Graphics

PNGs also support a lot more features than JPEG, as well as less destructive compression to boot.

**Review by no-lex — CHANGES_REQUESTED** [review]
You have useless `setshaderparam` lines in your two config files and `bumpspecdecal` is no longer appropriate without a specular texture.

**Comment by cloudziq** [comment]
bumpspecdecal is valid for decals and not require specular map.  with specmaps the bumpspecmapdecal should be used. Setshaderparam is needed in this case to not allow too much specular while in game, just a slight effect that overwrites underlying surface texture

**Comment by no-lex** [comment]
I thought you said you had wanted no specular at all.

**Comment by no-lex** [comment]
stddecals have no specular passthrough

**Comment by cloudziq** [comment]
I wanted slight effect so specs are not taken from underlying surface texture, just own speculars
with stddecal there nothing, no spec, no normals

**Comment by no-lex** [comment]
earlier: `> these two decals are supposed to not reflect any light.`, which is what I would consider a sane interpretation. I don't think I could justify any specular on decals like these, which are almost entirely diffuse by the nature of particle deposits left by water.

If you are insistent you want some specular, then the config files aren't wrong.

**Review by no-lex — APPROVED** [review]

**Pull request merged**
